### ISSUE TITLE
[Bug]: assertion `left != right` failed

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [mikumifa/biliTickerBuy#121]
### 部署方式

release的打包文件

### 版本

v2.8.0

### 异常情况

无法正常运行

### 报错信息

(base) PS C:\Users\Administrator\Desktop\main> .\bilibili-buy.exe
thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\git\checkouts\onnxruntime-rs-8c6c2f848739f72a\3a2b9bf\onnxruntime\src\lib.rs:180:5:
assertion `left != right` failed
  left: 0x0
 right: 0x0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "tab\go.py", line 24, in <module>
  File "geetest\AmorterValidator.py", line 18, in __init__
pyo3_runtime.PanicException: assertion `left != right` failed
  left: 0x0
 right: 0x0
[16672] Failed to execute script 'main' due to unhandled exception!

**Comment by Amorter** [comment]
什么问题，我这边也遇到了

**Comment by mikumifa** [comment]
那一行是  self.click = bili_ticket_gt_python.ClickPy() 
      这个会有概率出错吗
      
      要不要加一个retry

**Comment by Hoshino-Yumetsuki** [comment]
> ```
>   那一行是  self.click = bili_ticket_gt_python.ClickPy() 
>   这个会有概率出错吗
>   
>   要不要加一个retry
> ```

这个错误的出现环境是Windows Server 2022，使用Windows 11并未出现该错误（我本来想用服务器挂的qwq

**Comment by mikumifa** [comment]
ocr可能用的是系统自带的

**Comment by Amorter** [comment]
问题将在新版本解决

**Comment by Hoshino-Yumetsuki** [comment]
> ocr可能用的是系统自带的

可以尝试使用非系统ocr，系统ocr的话有些系统没有开启这个模块

**Comment by mikumifa** [comment]
v2.8.2应该解决了
