### ISSUE TITLE
[Bug]: 程序点击生成配置按钮时报错

### ISSUE THREAD

**Issue by cykchyk** [mikumifa/biliTickerBuy#169]
### 部署方式

release的打包文件

### 版本

Release v2.8.4-patch.3

### 异常情况

在浏览器点击生成配置时报错，问题可复现，页面也显示错误。
![8dfc98e165f3835839c97e0238e9919d](https://github.com/mikumifa/biliTickerBuy/assets/102507445/cc844e0b-9d13-4703-a845-227ee89c231f)
![b18a5d7dd3e2f24b208f2326b91a3d96](https://github.com/mikumifa/biliTickerBuy/assets/102507445/1966542e-6ddf-4fcf-a59b-f24a5f4f62e2)

### 报错信息

2024-06-27 13:49:17.622 | ERROR    | tab.settings:on_submit_all:202 - list indices must be integers or slices, not NoneType
Traceback (most recent call last):

  File "threading.py", line 1002, in _bootstrap

  File "threading.py", line 1045, in _bootstrap_inner

  File "anyio\_backends\_asyncio.py", line 859, in run

  File "C:\Users\cykch\Desktop\_internal\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
               │  │       └ {}
               │  └ ('https://show.bilibili.com/platform/detail.html?id=88102&from=pc_ticketlist', 0, [0], 0, None)
               └ <function on_submit_all at 0x0000020DCBD4BEC0>

> File "tab\settings.py", line 172, in on_submit_all

TypeError: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "C:\Users\cykch\Desktop\_internal\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cykch\Desktop\_internal\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cykch\Desktop\_internal\gradio\blocks.py", line 1938, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cykch\Desktop\_internal\gradio\blocks.py", line 1749, in postprocess_data
    prediction_value = postprocess_update_dict(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cykch\Desktop\_internal\gradio\blocks.py", line 615, in postprocess_update_dict
    update_dict["value"] = block.postprocess(value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cykch\Desktop\_internal\gradio\components\file.py", line 192, in postprocess
    orig_name=Path(value).name,
              ^^^^^^^^^^^
  File "pathlib.py", line 871, in __new__
  File "pathlib.py", line 509, in _from_parts
  File "pathlib.py", line 493, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not dict

**Comment by cykchyk** [comment]
点击获取票信息时正常

**Comment by WittF** [comment]
是不是地址没选

**Comment by mikumifa** [comment]
报错错了，实际上是漏填东西了

**Comment by mikumifa** [comment]
报错错了，实际上是漏填东西了
