### ISSUE TITLE
[Bug]: 老师今天我抢票有运行不了的问题

### ISSUE THREAD

**Issue by pocadawn** [mikumifa/biliTickerBuy#202]
### 部署方式

手动部署

### 版本

2.8.4

### 异常情况

网站显示有错误，控制台日志说账号存在异常。希望老师能告诉我是什么问题

### 报错信息

2024-06-29 11:16:44.794 | INFO     | tab.go:start_go:190 - 1）订单准备
2024-06-29 11:16:44.794 | INFO     | tab.go:start_go:191 - 请求头: {'Date': 'Sat, 29 Jun 2024 03:16:47 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '105', 'Connection': 'keep-alive', 'Server': 'nginx', 'Trace-Id': '3347616546', 'Expires': 'Sat, 29 Jun 2024 03:16:46 GMT', 'Cache-Control': 'no-cache', 'X-Cache-Webcdn': 'BYPASS from blzone01'} // 请求体: {'code': 100041, 'errno': 100041, 'errtag': 0, 'msg': '您的账号存在异常，暂时无法购票', 'data': {}}
2024-06-29 11:16:44.795 | ERROR    | tab.go:start_go:357 - 'token'
Traceback (most recent call last):

  File "threading.py", line 1002, in _bootstrap

  File "threading.py", line 1045, in _bootstrap_inner

  File "anyio\_backends\_asyncio.py", line 859, in run

  File "C:\Users\pocadawn\Downloads\bilibili-buy_v2.8.4-patch.3\_internal\gradio\utils.py", line 632, in run_sync_iterator_async
    return next(iterator)
                └ <generator object go_tab.<locals>.start_go at 0x000002878798FE20>

  File "C:\Users\pocadawn\Downloads\bilibili-buy_v2.8.4-patch.3\_internal\gradio\utils.py", line 815, in gen_wrapper
    response = next(iterator)
                    └ <generator object go_tab.<locals>.start_go at 0x0000028784897BA0>

> File "tab\go.py", line 288, in start_go

**Comment by mikumifa** [comment]
你是不是抢了bw，在开票前

**Comment by pocadawn** [comment]
提前抢票导致的吗，我设置的是定时，我就直接运行了。
感觉可能是我定时没设好，
如果封禁了大概几分钟可以好呀老师。

**Comment by pocadawn** [comment]
我好像明白了，谢谢老师

**Comment by 1093201139** [comment]
> 我好像明白了，谢谢老师

怎么回事 告诉一下呗 谢谢

**Comment by lllllis-02** [comment]
我貌似也有一样的问题呜呜呜呜
![image](https://github.com/mikumifa/biliTickerBuy/assets/156657335/0ffab287-6187-4198-8f90-e63aa4effa8a)

**Comment by mikumifa** [comment]
Discussion问吧，这isuee部分都是真bug
