### ISSUE TITLE
[Bug]: 抢票时报错

### ISSUE THREAD

**Issue by cykchyk** [mikumifa/biliTickerBuy#211]
### 部署方式

release的打包文件

### 版本

Release v2.8.4-patch.3

### 异常情况

抢票时报错

### 报错信息

2024-06-29 12:11:33.499 | INFO     | tab.go:start_go:190 - 1）订单准备
2024-06-29 12:11:33.500 | INFO     | tab.go:start_go:191 - 请求头: {'Date': 'Sat, 29 Jun 2024 04:11:33 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '407', 'Connection': 'keep-alive', 'Server': 'nginx', 'Trace-Id': '3676226383', 'Expires': 'Sat, 29 Jun 2024 04:11:32 GMT', 'Cache-Control': 'no-cache', 'X-Cache-Webcdn': 'BYPASS from blzone03'} // 请求体: {'code': 0, 'errno': 0, 'errtag': 0, 'msg': '', 'data': {'token': 'wGZ_iXUAAU-zAALDdwEAAwAHxIw.', 'projectName': None, 'screenName': None, 'projectImg': None, 'shield': {'open': 0}, 'ga_data': {'risk_level': 1, 'grisk_id': '58b3ce162e4ad8bb7e3c50c367667f89', 'decisions': [], 'riskParams': {'mid': None, 'decision_type': None, 'buvid': None, 'ip': None, 'api': None, 'origin_scene': None, 'scene': None, 'ua': None, 'v_voucher': None}, 'riskResult': 0}}}
2024-06-29 12:11:33.500 | INFO     | tab.go:start_go:297 - 2）创建订单
2024-06-29 12:11:33.559 | ERROR    | tab.go:start_go:357 - 429 Client Error: Too Many Requests for url: https://show.bilibili.com/api/ticket/order/createV2?project_id=85939
Traceback (most recent call last):

  File "threading.py", line 1002, in _bootstrap

  File "threading.py", line 1045, in _bootstrap_inner

  File "anyio\_backends\_asyncio.py", line 859, in run

  File "C:\Users\cykch\Desktop\_internal\gradio\utils.py", line 632, in run_sync_iterator_async
    return next(iterator)
                └ <generator object go_tab.<locals>.start_go at 0x000002224CBE8160>

  File "C:\Users\cykch\Desktop\_internal\gradio\utils.py", line 815, in gen_wrapper
    response = next(iterator)
                    └ <generator object go_tab.<locals>.start_go at 0x000002224991EC70>

> File "tab\go.py", line 300, in start_go

  File "util\BiliRequest.py", line 38, in post

  File "requests\models.py", line 1021, in raise_for_status

**Comment by mikumifa** [comment]
人太多了，脚本也挤不进去
