### ISSUE TITLE
[Bug]:2024-07-01 16:11:56.955 | ERROR    | tab.go:start_go:413 - 'token'

### ISSUE THREAD

**Issue by Beluga0101** [mikumifa/biliTickerBuy#334]
### 部署方式

release的打包文件

### 版本

bilibili-buy_v2.8.5 bilibili-buy_v2.8.5-patch.2 bilibili-buy_v2.8.5-patch.3

### 异常情况

2024-07-01 16:11:56.955 | ERROR    | tab.go:start_go:413 - 'token'
Traceback (most recent call last):

  File "threading.py", line 1002, in _bootstrap

  File "threading.py", line 1045, in _bootstrap_inner

  File "anyio\_backends\_asyncio.py", line 859, in run

  File "C:\Users\Administrator\Desktop\bilibili-buy_v2.8.5-patch.3\_internal\gradio\utils.py", line 632, in run_sync_iterator_async
    return next(iterator)
                └ <generator object go_tab.<locals>.start_go at 0x0000010E16F51240>

  File "C:\Users\Administrator\Desktop\bilibili-buy_v2.8.5-patch.3\_internal\gradio\utils.py", line 815, in gen_wrapper
    response = next(iterator)
                    └ <generator object go_tab.<locals>.start_go at 0x0000010E15EA5720>

> File "tab\go.py", line 314, in start_go

KeyError: 'token'

### 报错信息

2024-07-01 16:11:56.955 | ERROR    | tab.go:start_go:413 - 'token'
Traceback (most recent call last):

  File "threading.py", line 1002, in _bootstrap

  File "threading.py", line 1045, in _bootstrap_inner

  File "anyio\_backends\_asyncio.py", line 859, in run

  File "C:\Users\Administrator\Desktop\bilibili-buy_v2.8.5-patch.3\_internal\gradio\utils.py", line 632, in run_sync_iterator_async
    return next(iterator)
                └ <generator object go_tab.<locals>.start_go at 0x0000010E16F51240>

  File "C:\Users\Administrator\Desktop\bilibili-buy_v2.8.5-patch.3\_internal\gradio\utils.py", line 815, in gen_wrapper
    response = next(iterator)
                    └ <generator object go_tab.<locals>.start_go at 0x0000010E15EA5720>

> File "tab\go.py", line 314, in start_go

KeyError: 'token'

**Comment by mikumifa** [comment]
抢到票不存在

**Comment by luotian2020** [comment]
> 抢到票不存在

这是今天上午使用中遇到的部分日志信息：请求头: {'Date': 'Mon, 01 Jul 2024 04:00:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '94', 'Connection': 'keep-alive', 'Server': 'nginx', 'Trace-Id': '3710189782', 'Expires': 'Mon, 01 Jul 2024 04:00:30 GMT', 'Cache-Control': 'no-cache', 'X-Cache-Webcdn': 'BYPASS from blzone03'} // 请求体: {'code': 100039, 'errno': 100039, 'errtag': 0, 'msg': '活动收摊啦,下次要快点哦', 'data': {}}

**Comment by luotian2020** [comment]
应该改一下接口返回结果就行接口返回结果就行

**Comment by mikumifa** [comment]
你抢错票了，今天中午只有联票
