### ISSUE TITLE
[Bug]: [9576] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!

### ISSUE THREAD

**Issue by Beluga0101** [mikumifa/biliTickerBuy#357]
### 部署方式

手动部署

### 版本

bilibili-buy_v2.8.6

### 异常情况

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 187, in get_code
  File "PyInstaller\loader\pyimod01_archive.py", line 134, in extract
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\Desktop\\bilibili-buy_v2.8.6\\bilibili-buy.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\parser.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\feedparser.py", line 27, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\_policybase.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\utils.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "random.py", line 56, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 400, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 189, in get_code
ImportError: PyiFrozenImporter cannot handle module 'bisect'
[9576] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!

### 报错信息

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 187, in get_code
  File "PyInstaller\loader\pyimod01_archive.py", line 134, in extract
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\Desktop\\bilibili-buy_v2.8.6\\bilibili-buy.exe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\parser.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\feedparser.py", line 27, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\_policybase.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "email\utils.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "random.py", line 56, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 400, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 189, in get_code
ImportError: PyiFrozenImporter cannot handle module 'bisect'
[9576] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!

**Comment by Beluga0101** [comment]
试过了，关闭clash就好了，不知道是不是端口冲突
