### ISSUE TITLE
[Bug]: 生成配置文件报错

### ISSUE THREAD

**Issue by xmbhjQAQ** [mikumifa/biliTickerBuy#420]
### 部署方式

手动部署

### 版本

2.8.8-patch1

### 异常情况

当我在获取票信息的时候报了值传递错误，初步看控制台好像是传了一个字典到Calendar的postprocess，而传进去的应该是datetime.datetime() .
以下为报错信息：
```python
  Traceback (most recent call last):
  File "D:\bilibili-buy\_internal\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilibili-buy\_internal\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilibili-buy\_internal\gradio\blocks.py", line 1938, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilibili-buy\_internal\gradio\blocks.py", line 1749, in postprocess_data
    prediction_value = postprocess_update_dict(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilibili-buy\_internal\gradio\blocks.py", line 615, in postprocess_update_dict
    update_dict["value"] = block.postprocess(value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "gradio_calendar\calendar.py", line 66, in postprocess
ValueError: Unexpected value type <class 'dict'> for Calender (value: {'__type__': 'update'})
```

经测试，该问题在release版本和仓库版本均稳定复现

**Comment by mikumifa** [comment]
测试一下新的patch.1

**Comment by mikumifa** [comment]
大概5分钟后

**Comment by xmbhjQAQ** [comment]
Ok

**Comment by xmbhjQAQ** [comment]
问题依旧（）

**Comment by xmbhjQAQ** [comment]
```python
Traceback (most recent call last):
  File "C:\Users\xmbhjQAQ\Downloads\Compressed\bilibili-buy_v2.8.8-patch.1\_internal\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xmbhjQAQ\Downloads\Compressed\bilibili-buy_v2.8.8-patch.1\_internal\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xmbhjQAQ\Downloads\Compressed\bilibili-buy_v2.8.8-patch.1\_internal\gradio\blocks.py", line 1938, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xmbhjQAQ\Downloads\Compressed\bilibili-buy_v2.8.8-patch.1\_internal\gradio\blocks.py", line 1749, in postprocess_data
    prediction_value = postprocess_update_dict(
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xmbhjQAQ\Downloads\Compressed\bilibili-buy_v2.8.8-patch.1\_internal\gradio\blocks.py", line 615, in postprocess_update_dict
    update_dict["value"] = block.postprocess(value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xmbhjQAQ\Downloads\Compressed\bilibili-buy_v2.8.8-patch.1\_internal\gradio_calendar\calendar.py", line 66, in postprocess
    raise ValueError(f"Unexpected value type {type(value)} for Calender (value: {value})")
ValueError: Unexpected value type <class 'dict'> for Calender (value: {'__type__': 'update'})
```

**Comment by mikumifa** [comment]
给个测试用例？

**Comment by mikumifa** [comment]
我测试没出现问题

**Comment by xmbhjQAQ** [comment]
https://show.bilibili.com/platform/detail.html?id=91180

**Comment by xmbhjQAQ** [comment]
奇了怪了

**Comment by mikumifa** [comment]
等patch.2

**Comment by mikumifa** [comment]
新加的日历功能侵入性太强了，把以前的给改坏了

**Comment by xmbhjQAQ** [comment]
问题已解决，感谢
