### ISSUE TITLE
大佬，为啥我用不了啊

### ISSUE THREAD

**Issue by yuanyf23** [mikumifa/biliTickerBuy#443]
显示的错误为：
Traceback (most recent call last):
  File "C:\Users\yuany\Downloads\Bilibili_show_ticket_auto_order-main\Bilibili_show_ticket_auto_order-main\main.py", line 21, in <module>
    Api(proxies=proxies,specificID=specificID,sleepTime=sleep,token=token).start()
  File "C:\Users\yuany\Downloads\Bilibili_show_ticket_auto_order-main\Bilibili_show_ticket_auto_order-main\api.py", line 422, in start
    if self.tokenGet() == 0:
       ^^^^^^^^^^^^^^^
  File "C:\Users\yuany\Downloads\Bilibili_show_ticket_auto_order-main\Bilibili_show_ticket_auto_order-main\api.py", line 188, in tokenGet
    if data["data"]["shield"]["verifyMethod"]:
       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'verifyMethod'

**Comment by mikumifa** [comment]
这不是我的程序哦
