### ISSUE TITLE
[Bug]: requirements.txt缺少playsound包

### ISSUE THREAD

**Issue by LingkongSky** [mikumifa/biliTickerBuy#448]
### 部署方式

手动部署

### 版本

当前版本

### 异常情况

在进行容器构建后运行时，反馈缺少playsound模块报错，建议在requirements中添加playsound==1.3.0

### 报错信息

2024-11-14 22:00:55.362 | INFO     | config:<module>:34 - 设置路径, APP_PATH=/app TEMP_PATH=/app/tmp BASE_DIR=/usr/local/bin
2024-11-14 22:00:55.409 | INFO     | util.TimeService:compute_timeoffset:27 - 时间同步成功, 将使用ntp.aliyun.com时间
2024-11-14 22:00:55.409 | INFO     | util.TimeService:set_timeoffset:40 - 设置时间偏差为: 0.00122秒
Traceback (most recent call last):
  File "/app/main.py", line 8, in <module>
    from tab.go import go_tab
  File "/app/tab/go.py", line 22, in <module>
    from util import PushPlusUtil
  File "/app/util/PushPlusUtil.py", line 5, in <module>
    import playsound
ModuleNotFoundError: No module named 'playsound'

**Comment by LingkongSky** [comment]
在使用pipreq重新生成requirements.txt后经测试可正常构建运行：

```
gradio==5.5.0
gradio_calendar==0.0.6
loguru==0.7.2
ntplib==0.4.0
playsound==1.3.0
playwright==1.48.0
qrcode==8.0
Requests==2.32.3
retry==0.9.2
tinydb==4.8.2
```

**Comment by mikumifa** [comment]
新版本一个没有playsound了，可以把playsound先给删了
