### ISSUE TITLE
[Bug]: 打开软件后刚弹出彩色的UI就关闭了

### ISSUE THREAD

**Issue by YokeLYun** [mikumifa/biliTickerBuy#68]
### 部署方式

手动部署

### 版本

v2.5.4

### 异常情况

先启动浏览器一会儿然后弹出UI就瞬间没了，也没跳什么错误代码什么的

**Comment by mikumifa** [comment]
给具体内容，截图都需要

**Comment by YokeLYun** [comment]
> 给具体内容，截图都需要


https://github.com/mikumifa/biliTickerBuy/assets/167688830/cb4cab24-dca2-4316-8aa1-124ea3da965f

就类似这样

**Comment by mikumifa** [comment]
app.log日志文件可以看看么，里面会有详细的报错

**Comment by YokeLYun** [comment]
> app.log日志文件可以看看么，里面会有详细的报错

2024-05-07 19:51:27.383 | INFO     | util.config_util:_login_and_save_cookies:24 - 启动浏览器中.....
2024-05-07 19:51:35.065 | ERROR    | util.config_util:get_cookies:64 - An error has been caught in function 'get_cookies', process 'MainProcess' (27320), thread 'MainThread' (13956):
Traceback (most recent call last):

  File "util\config_util.py", line 61, in get_cookies

FileNotFoundError: [Errno 2] No such file or directory: 'E:\\脚本\\bilibili-buy\\main\\_internal\\cookies.json'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "urllib3\connectionpool.py", line 467, in _make_request

  File "urllib3\connectionpool.py", line 1099, in _validate_conn

  File "urllib3\connection.py", line 653, in connect

  File "urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname

  File "urllib3\util\ssl_.py", line 465, in ssl_wrap_socket

  File "urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl

  File "ssl.py", line 517, in wrap_socket

  File "ssl.py", line 1104, in _create

  File "ssl.py", line 1382, in do_handshake

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "urllib3\connectionpool.py", line 793, in urlopen

  File "urllib3\connectionpool.py", line 491, in _make_request

urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "requests\adapters.py", line 486, in send

  File "urllib3\connectionpool.py", line 847, in urlopen

  File "urllib3\util\retry.py", line 515, in increment

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='msedgedriver.azureedge.net', port=443): Max retries exceeded with url: /LATEST_RELEASE_124_WINDOWS (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "webdriver_manager\core\http.py", line 32, in get

  File "requests\api.py", line 73, in get

  File "requests\api.py", line 59, in request

  File "requests\sessions.py", line 589, in request

  File "requests\sessions.py", line 703, in send

  File "requests\adapters.py", line 517, in send

requests.exceptions.SSLError: HTTPSConnectionPool(host='msedgedriver.azureedge.net', port=443): Max retries exceeded with url: /LATEST_RELEASE_124_WINDOWS (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "util\config_util.py", line 26, in _login_and_save_cookies

  File "webdriver_manager\microsoft.py", line 73, in install

  File "webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path

  File "webdriver_manager\core\driver_cache.py", line 105, in find_driver

  File "webdriver_manager\core\driver_cache.py", line 152, in get_cache_key_driver_version

  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download

  File "webdriver_manager\drivers\edge.py", line 51, in get_latest_release_version

  File "webdriver_manager\core\http.py", line 35, in get

requests.exceptions.ConnectionError: Could not reach host. Are you offline?


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "util\config_util.py", line 29, in _login_and_save_cookies

  File "webdriver_manager\chrome.py", line 40, in install

  File "webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path

  File "webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url

  File "webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download

  File "webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version

AttributeError: 'NoneType' object has no attribute 'split'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "main.py", line 31, in <module>

  File "tab\train.py", line 9, in train_tab

  File "util\bili_request.py", line 10, in __init__

  File "util\config_util.py", line 72, in get_cookies_str

> File "util\config_util.py", line 64, in get_cookies

  File "util\config_util.py", line 31, in _login_and_save_cookies

Exception: 没有找到浏览器驱动，请根据自己的浏览器下载相应的驱动：
相关教程：https://blog.csdn.net/zz00008888/article/details/127903475
Edge： https://liushilive.github.io/github_selenium_drivers/md/IE.html
Chrome：https://liushilive.github.io/github_selenium_drivers/md/Chrome.html

**Comment by mikumifa** [comment]
https://github.com/mikumifa/biliTickerBuy/wiki/%E6%B5%8F%E8%A7%88%E5%99%A8%E9%A9%B1%E5%8A%A8%E5%AE%89%E8%A3%85%E5%87%BA%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E5%BC%8F
