### ISSUE TITLE
提示请 `请慢一点`

### ISSUE THREAD

**Issue by Lrrrrrrt** [mikumifa/biliTickerBuy#71]
### 部署方式

手动部署

### 版本

2.6.0

### 异常情况

下单提示过快
![1716728446404](https://github.com/mikumifa/biliTickerBuy/assets/108092864/26950e57-0c62-452e-ad0f-091d9a5cf02c)

### 报错信息

2024-05-25 19:00:00.416 | INFO     | tab.go:start_go:65 - prepare header: {'Date': 'Sat, 25 May 2024 11:00:00 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '72', 'Connection': 'keep-alive', 'Server': 'nginx', 'Trace-Id': '2227197545', 'Expires': 'Sat, 25 May 2024 10:59:59 GMT', 'Cache-Control': 'no-cache', 'X-Cache-Webcdn': 'BYPASS from blzone04'}
2024-05-25 19:00:00.416 | INFO     | tab.go:start_go:66 - prepare: {'code': 100001, 'errno': 100001, 'errtag': 0, 'msg': '请慢一点', 'data': {}}
2024-05-25 19:00:00.416 | ERROR    | tab.go:start_go:188 - 'token'
Traceback (most recent call last):

  File "threading.py", line 1002, in _bootstrap

  File "threading.py", line 1045, in _bootstrap_inner

  File "anyio\_backends\_asyncio.py", line 851, in run

  File "C:\Users\87017\Desktop\新建文件夹 (3)\main\_internal\gradio\utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
                └ <generator object start_go at 0x00000200B48E7880>

  File "C:\Users\87017\Desktop\新建文件夹 (3)\main\_internal\gradio\utils.py", line 742, in gen_wrapper
    response = next(iterator)
                    └ <generator object start_go at 0x00000200B48F9120>

> File "tab\go.py", line 123, in start_go

**Comment by mikumifa** [comment]
应该不会准时抢还被风控的吧

**Comment by Lrrrrrrt** [comment]
> 应该不会准时抢还被风控的吧

我想下单的是一个19.00的马正阳的内场票，我设置的任务时间也是19.00，但是提示我的是‘请慢一点’，一直下不了单但请问这种是风控问题吗，还是我的号的问题啊？
我设置的顺序是先  配置好抢票信息---训练验证码速度----填入抢票信息，定时抢票，步骤应该没问题吧？？

**Comment by Andy-Chuck** [comment]
间隔太短了吗？

还有注意遮挡一下个人信息

**Comment by Lrrrrrrt** [comment]
> 间隔太短了吗？ 还有注意遮挡一下个人信息

谢谢 我间隔时间设置的就是默认的，没有更改，请问你最近用这个软件能正常 下单吗

**Comment by Andy-Chuck** [comment]
#67 提到不足5s就会提示慢一点，试试设置为5000以上，账号一般不会被黑，IP被黑也不是提示这个

**Comment by Lrrrrrrt** [comment]
> #67 提到不足5s就会提示慢一点，试试设置为5000以上，账号一般不会被黑，IP被黑也不是提示这个

嗯嗯 谢谢佬

**Comment by Lrrrrrrt** [comment]
> 应该不会准时抢还被风控的吧

佬，我刚刚测试了我定时了23.00的时间，但是会员购订单成功下单时间是22.59.59
![294c1c7bb5ff72bfb5c20a0ec3d1bde](https://github.com/mikumifa/biliTickerBuy/assets/108092864/55cc5ed6-27bc-4429-b52c-ff6d8fe398c4)

**Comment by Lrrrrrrt** [comment]
> #67 提到不足5s就会提示慢一点，试试设置为5000以上，账号一般不会被黑，IP被黑也不是提示这个

佬，我刚刚测试了我定时了23.00的时间，但是会员购订单成功下单时间是22.59.59
![Uploading 294c1c7bb5ff72bfb5c20a0ec3d1bde.png…]()

**Comment by Andy-Chuck** [comment]
要么睿站服务器时间有问题要么你的时间有问题Message ID: ***@***.***>

**Comment by mikumifa** [comment]
@Lrrrrrrt 
- 如果是整点抢的话，像这种时间还没到的应该会失败。不过程序会一直重复抢票，所以这种情况不用担心，程序会一直重复发送请求，直到抢到
- 还有就是 `请慢一点` 这个提示，就是因为当时抢票的人太多了，b站阻止拒绝了这次订单请求，这种情况下，我这个程序也无能为力。这个程序的作用就是能准时发送订单请求，至于能不能真正的抢到，运气和网速等其他原因也是很重要的 

> 开票后0.4s后发请求还被拒绝了，这真的合理吗
